/*
 * Copyright (C) 2011 Michael Thomas <michael4.thomas@live.uwe.ac.uk>
 *
 * This file is part of FAHView.
 *
 * FAHView is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * FAHView is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with FAHView.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.fahview;

import com.fahview.controller.LogReader;
import java.awt.BorderLayout;
import javax.swing.JTable;

/**
 * The main User Interface of the FAHView program.
 * 
 * @author <a href="mailto:michael4.thomas@live.uwe.ac.uk">Michael Thomas</a>
 */
public class UI extends javax.swing.JFrame {

    /**
     * Get this Queue table instance
     * 
     * @return JTable table
     */
    public JTable getTable() {
        return table;
    }

    /**
     * Set the Status value in the Queue table to a specified value at the
     * required position
     * 
     * @param position location in the table to change value.
     * @param value the value to change to
     */
    protected void setStatus(int position, int value) {
        table.getModel().setValueAt(value, position, 1);
    }

    /**
     * Set the Percentage value in the Queue table to a specified value at the
     * required position
     * 
     * @param position location in the table to change value.
     * @param value the value to change to
     */
    protected void setPercentage(int position, String value) {
        table.getModel().setValueAt(value, position, 2);
    }
    
    /**
     * Set the Project value in the Queue table to a specified value at the
     * required position
     * 
     * @param position location in the table to change value.
     * @param value the value to change to
     */
    protected void setProject(int position, String value) {
        table.getModel().setValueAt(value, position, 3);
    }
    
    /**
     * Set the Issue time for the current work unit
     * 
     * @param issued the issue time for current work unit
     */
    protected void setIssued(String issued) {
        this.issued.setText(issued);
    }
    
    /**
     * Set the Work server for the current work unit
     * 
     * @param workServer the work server for current work unit
     */
    protected void setWorkServer(String workServer) {
        this.workServer.setText(workServer);
    }
    
    /**
     * Set the Collection server for the current work unit
     * 
     * @param collectionServer the collection server for current work unit
     */
    protected void setCollectionServer(String collectionServer) {
        this.collectionServer.setText(collectionServer);
    }
    
    /**
     * Set the User Name for the current work unit
     * 
     * @param userName the user name for current work unit
     */
    protected void setUserName(String userName) {
        this.userName.setText(userName);
    }
    
    /**
     * Set the Team Number for the current work unit
     * 
     * @param teamNumber the team number for current work unit
     */
    protected void setTeamNumber(String teamNumber) {
        this.teamNumber.setText(teamNumber);
    }
    
    /**
     * Set the Core Type for the current work unit
     * 
     * @param core the core type for current work unit
     */
    protected void setCore(String core) {
        this.core.setText(core);
    }

    /**
     * Creates new form UI
     *
     * @param location the file path of the client working directory
     */
    public UI(String location) {
        initComponents();
        table.getColumn("Progress").setCellRenderer(new ProgressCellRenderer());

        // Add Jmol panel
        JmolPanel jmol = new JmolPanel();
        jmolPanel.setLayout(new BorderLayout());
        jmolPanel.add(jmol);
        
        // Set model and get info
        jmol.viewer.openFile(location + "/work/current.xyz");
        System.out.println(
                jmol.viewer.getProperty("readable", "modelInfo", null));
        System.out.println(
                jmol.viewer.getProperty("readable", "auxiliaryInfo", null));
        
        // Populate log window
        LogReader logReader = new LogReader(location);
        log.setText(logReader.toString());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        clientPanel = new javax.swing.JPanel();
        addClient = new javax.swing.JButton();
        deleteClient = new javax.swing.JButton();
        clientPane = new javax.swing.JScrollPane();
        clientList = new javax.swing.JTree();
        detailsPane = new javax.swing.JTabbedPane();
        detailsPanel = new javax.swing.JPanel();
        queueWindow = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        logWindow = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        currentWU = new javax.swing.JInternalFrame();
        issuedLabel = new javax.swing.JLabel();
        workServerLabel = new javax.swing.JLabel();
        collectionServerLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        TeamNumberLabel = new javax.swing.JLabel();
        issued = new javax.swing.JLabel();
        workServer = new javax.swing.JLabel();
        collectionServer = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        teamNumber = new javax.swing.JLabel();
        coreLabel = new javax.swing.JLabel();
        core = new javax.swing.JLabel();
        jmolPanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAHView");

        splitPane.setDividerLocation(250);
        splitPane.setEnabled(false);

        addClient.setText("Add Client");

        deleteClient.setText("Delete Client");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Client 1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 0");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 5");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 6");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 7");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 8");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 9");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Client 2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 0");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 5");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 6");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 7");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 8");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 9");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Client 3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 0");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 1");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 2");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 3");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 4");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 5");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 6");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 7");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 8");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("QueueIndex 9");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        clientList.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        clientList.setRootVisible(false);
        clientPane.setViewportView(clientList);

        org.jdesktop.layout.GroupLayout clientPanelLayout = new org.jdesktop.layout.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(clientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(clientPane)
                    .add(clientPanelLayout.createSequentialGroup()
                        .add(addClient, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(deleteClient, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(clientPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clientPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addClient)
                    .add(deleteClient)))
        );

        splitPane.setLeftComponent(clientPanel);

        detailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", null, "0%", null},
                {"1", null, "0%", null},
                {"2", null, "0%", null},
                {"3", null, "0%", null},
                {"4", null, "0%", null},
                {"5", null, "0%", null},
                {"6", null, "0%", null},
                {"7", null, "0%", null},
                {"8", null, "0%", null},
                {"9", null, "0%", null}
            },
            new String [] {
                "Position", "Status", "Progress", "Project"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setEnabled(false);
        queueWindow.setViewportView(table);
        table.getColumnModel().getColumn(0).setResizable(false);
        table.getColumnModel().getColumn(0).setPreferredWidth(25);
        table.getColumnModel().getColumn(1).setResizable(false);
        table.getColumnModel().getColumn(1).setPreferredWidth(25);
        table.getColumnModel().getColumn(2).setResizable(false);
        table.getColumnModel().getColumn(2).setPreferredWidth(50);
        table.getColumnModel().getColumn(3).setResizable(false);
        table.getColumnModel().getColumn(3).setPreferredWidth(200);

        log.setColumns(20);
        log.setRows(5);
        logWindow.setViewportView(log);

        currentWU.setVisible(true);

        issuedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        issuedLabel.setText("Issued:");

        workServerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        workServerLabel.setText("Work Server:");

        collectionServerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        collectionServerLabel.setText("Collection Server:");

        UserNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserNameLabel.setText("User Name:");

        TeamNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TeamNumberLabel.setText("Team Number:");

        coreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        coreLabel.setText("Core:");

        org.jdesktop.layout.GroupLayout currentWULayout = new org.jdesktop.layout.GroupLayout(currentWU.getContentPane());
        currentWU.getContentPane().setLayout(currentWULayout);
        currentWULayout.setHorizontalGroup(
            currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(currentWULayout.createSequentialGroup()
                .addContainerGap()
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(currentWULayout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(coreLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, UserNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(issuedLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(workServerLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(collectionServerLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, TeamNumberLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(issued, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(workServer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(collectionServer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(userName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(teamNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(core, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap())
        );
        currentWULayout.setVerticalGroup(
            currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(currentWULayout.createSequentialGroup()
                .addContainerGap()
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(issuedLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(issued, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(workServerLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(workServer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(collectionServerLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(collectionServer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(UserNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(userName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TeamNumberLabel)
                    .add(teamNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWULayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(coreLabel)
                    .add(core, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout detailsPanelLayout = new org.jdesktop.layout.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(logWindow)
            .add(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(queueWindow, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currentWU, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(detailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(queueWindow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(currentWU))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(logWindow, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
        );

        detailsPane.addTab("Details", detailsPanel);

        jmolPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jmolPanel.setPreferredSize(new java.awt.Dimension(200, 200));

        org.jdesktop.layout.GroupLayout jmolPanelLayout = new org.jdesktop.layout.GroupLayout(jmolPanel);
        jmolPanel.setLayout(jmolPanelLayout);
        jmolPanelLayout.setHorizontalGroup(
            jmolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 689, Short.MAX_VALUE)
        );
        jmolPanelLayout.setVerticalGroup(
            jmolPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 387, Short.MAX_VALUE)
        );

        detailsPane.addTab("3D Model", jmolPanel);

        splitPane.setRightComponent(detailsPane);

        file.setText("File");

        quit.setText("Quit");
        file.add(quit);

        mainMenu.add(file);

        help.setText("Help");
        mainMenu.add(help);

        setJMenuBar(mainMenu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(splitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeamNumberLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton addClient;
    private javax.swing.JTree clientList;
    private javax.swing.JScrollPane clientPane;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JLabel collectionServer;
    private javax.swing.JLabel collectionServerLabel;
    private javax.swing.JLabel core;
    private javax.swing.JLabel coreLabel;
    private javax.swing.JInternalFrame currentWU;
    private javax.swing.JButton deleteClient;
    private javax.swing.JTabbedPane detailsPane;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JLabel issued;
    private javax.swing.JLabel issuedLabel;
    private javax.swing.JPanel jmolPanel;
    private javax.swing.JTextArea log;
    private javax.swing.JScrollPane logWindow;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JScrollPane queueWindow;
    private javax.swing.JMenuItem quit;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTable table;
    private javax.swing.JLabel teamNumber;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel workServer;
    private javax.swing.JLabel workServerLabel;
    // End of variables declaration//GEN-END:variables
}
